"""add owner active status

Revision ID: 22f0b868ef64
Revises: e286a73b2c31
Create Date: 2026-09-19 08:44:03.002628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f0b868ef64'
down_revision: Union[str, Sequence[str], None] = 'e286a73b2c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_owners_is_active'), 'owners', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owners_is_active'), table_name='owners')
    op.drop_column('owners', 'is_active')
    # ### end Alembic commands ###
