"""perf: add owner and unit indexes

Revision ID: 6195dad55b47
Revises: fcf853b52174
Create Date: 2026-09-18 13:24:26.281497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6195dad55b47'
down_revision: Union[str, Sequence[str], None] = 'fcf853b52174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_owners_name'), 'owners', ['name'], unique=False)
    op.create_index(op.f('ix_units_unit_number'), 'units', ['unit_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_unit_number'), table_name='units')
    op.drop_index(op.f('ix_owners_name'), table_name='owners')
    # ### end Alembic commands ###
