"""allow duplicate unit codes

Revision ID: 9c79a9b4bd8a
Revises: f8471e3515c3
Create Date: 2026-09-17 01:47:35.116352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c79a9b4bd8a'
down_revision: Union[str, Sequence[str], None] = 'f8471e3515c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ownership_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ownership_history_source_order_id'), 'ownership_history', ['source_order_id'], unique=False)
    op.drop_index(op.f('ix_units_unit_code'), table_name='units')
    op.create_index(op.f('ix_units_unit_code'), 'units', ['unit_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_unit_code'), table_name='units')
    op.create_index(op.f('ix_units_unit_code'), 'units', ['unit_code'], unique=True)
    op.drop_index(op.f('ix_ownership_history_source_order_id'), table_name='ownership_history')
    op.alter_column('ownership_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
