"""create core registry tables

Revision ID: cf5496d8475e
Revises: 
Create Date: 2026-09-17 00:31:27.004882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5496d8475e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.String(length=150), nullable=False),
    sa.Column('area_name', sa.String(length=150), nullable=True),
    sa.Column('community', sa.String(length=150), nullable=True),
    sa.Column('project', sa.String(length=150), nullable=True),
    sa.Column('project_land', sa.String(length=150), nullable=True),
    sa.Column('building_no', sa.String(length=100), nullable=True),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_locations_community'), 'locations', ['community'], unique=False)
    op.create_table('owners',
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id_number', sa.String(length=100), nullable=True),
    sa.Column('uae_id_number', sa.String(length=100), nullable=True),
    sa.Column('unified_number', sa.String(length=100), nullable=True),
    sa.Column('passport_expiry_date', sa.Date(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('record_id')
    )
    op.create_index(op.f('ix_owners_normalized_name'), 'owners', ['normalized_name'], unique=False)
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('contact_type', sa.String(length=30), nullable=False),
    sa.Column('contact_value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index(op.f('ix_contacts_owner_id'), 'contacts', ['owner_id'], unique=False)
    op.create_table('units',
    sa.Column('unit_id', sa.String(length=150), nullable=False),
    sa.Column('property_id', sa.String(length=150), nullable=True),
    sa.Column('unit_code', sa.String(length=150), nullable=True),
    sa.Column('unit_number', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.String(length=150), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('dm_no', sa.String(length=100), nullable=True),
    sa.Column('dm_sub_no', sa.String(length=100), nullable=True),
    sa.Column('land_sub_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_units_location_id'), 'units', ['location_id'], unique=False)
    op.create_index(op.f('ix_units_property_id'), 'units', ['property_id'], unique=True)
    op.create_index(op.f('ix_units_unit_code'), 'units', ['unit_code'], unique=True)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=150), nullable=False),
    sa.Column('source_regis', sa.String(length=150), nullable=True),
    sa.Column('unit_id', sa.String(length=150), nullable=True),
    sa.Column('location_id', sa.String(length=150), nullable=True),
    sa.Column('procedure_name', sa.String(length=255), nullable=True),
    sa.Column('procedure_value', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_location_id'), 'orders', ['location_id'], unique=False)
    op.create_index(op.f('ix_orders_source_regis'), 'orders', ['source_regis'], unique=False)
    op.create_index(op.f('ix_orders_unit_id'), 'orders', ['unit_id'], unique=False)
    op.create_table('order_parties',
    sa.Column('order_party_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=150), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('source_row_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.PrimaryKeyConstraint('order_party_id')
    )
    op.create_index(op.f('ix_order_parties_order_id'), 'order_parties', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_parties_owner_id'), 'order_parties', ['owner_id'], unique=False)
    op.create_table('ownership_history',
    sa.Column('ownership_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.String(length=150), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_order_id', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.ForeignKeyConstraint(['source_order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], ),
    sa.PrimaryKeyConstraint('ownership_history_id')
    )
    op.create_index(op.f('ix_ownership_history_owner_id'), 'ownership_history', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ownership_history_unit_id'), 'ownership_history', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ownership_history_unit_id'), table_name='ownership_history')
    op.drop_index(op.f('ix_ownership_history_owner_id'), table_name='ownership_history')
    op.drop_table('ownership_history')
    op.drop_index(op.f('ix_order_parties_owner_id'), table_name='order_parties')
    op.drop_index(op.f('ix_order_parties_order_id'), table_name='order_parties')
    op.drop_table('order_parties')
    op.drop_index(op.f('ix_orders_unit_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_source_regis'), table_name='orders')
    op.drop_index(op.f('ix_orders_location_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_units_unit_code'), table_name='units')
    op.drop_index(op.f('ix_units_property_id'), table_name='units')
    op.drop_index(op.f('ix_units_location_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_contacts_owner_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_owners_normalized_name'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_locations_community'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
