"""expand owner profile attributes

Revision ID: e286a73b2c31
Revises: 6195dad55b47
Create Date: 2026-09-19 00:41:45.007193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e286a73b2c31'
down_revision: Union[str, Sequence[str], None] = '6195dad55b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('owners', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('owners', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('owners', sa.Column('vip_tier', sa.String(length=50), nullable=True))
    op.add_column('owners', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('owners', sa.Column('gender_source', sa.String(length=50), nullable=True))
    op.add_column('owners', sa.Column('source_community', sa.String(length=255), nullable=True))
    op.add_column('owners', sa.Column('source_file', sa.String(length=500), nullable=True))
    op.add_column('owners', sa.Column('property_count', sa.Integer(), nullable=True))
    op.add_column('owners', sa.Column('communities_owned', sa.Integer(), nullable=True))
    op.add_column('owners', sa.Column('community_list', sa.Text(), nullable=True))
    op.add_column('owners', sa.Column('buildings_list', sa.Text(), nullable=True))
    op.add_column('owners', sa.Column('is_multi_property', sa.Boolean(), nullable=True))
    op.add_column('owners', sa.Column('is_portfolio_investor', sa.Boolean(), nullable=True))
    op.add_column('owners', sa.Column('has_cross_community', sa.Boolean(), nullable=True))
    op.add_column('owners', sa.Column('portfolio_tier', sa.String(length=100), nullable=True))
    op.add_column('owners', sa.Column('has_plot', sa.Boolean(), nullable=True))
    op.add_column('owners', sa.Column('has_apartment', sa.Boolean(), nullable=True))
    op.add_column('owners', sa.Column('has_villa', sa.Boolean(), nullable=True))
    op.add_column('owners', sa.Column('is_reachable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'is_reachable')
    op.drop_column('owners', 'has_villa')
    op.drop_column('owners', 'has_apartment')
    op.drop_column('owners', 'has_plot')
    op.drop_column('owners', 'portfolio_tier')
    op.drop_column('owners', 'has_cross_community')
    op.drop_column('owners', 'is_portfolio_investor')
    op.drop_column('owners', 'is_multi_property')
    op.drop_column('owners', 'buildings_list')
    op.drop_column('owners', 'community_list')
    op.drop_column('owners', 'communities_owned')
    op.drop_column('owners', 'property_count')
    op.drop_column('owners', 'source_file')
    op.drop_column('owners', 'source_community')
    op.drop_column('owners', 'gender_source')
    op.drop_column('owners', 'gender')
    op.drop_column('owners', 'vip_tier')
    op.drop_column('owners', 'title')
    op.drop_column('owners', 'last_name')
    op.drop_column('owners', 'first_name')
    # ### end Alembic commands ###
