"""perf: index ownership history created at

Revision ID: fcf853b52174
Revises: 9c79a9b4bd8a
Create Date: 2026-09-17 16:21:38.021890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf853b52174'
down_revision: Union[str, Sequence[str], None] = '9c79a9b4bd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ownership_history_created_at'), 'ownership_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ownership_history_created_at'), table_name='ownership_history')
    # ### end Alembic commands ###
